blog/urls.py
from django.urls import include, path # re_path 
from . import views
from .feeds import LatestPostsFeed


app_name = 'blog' # an application namespace
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', # use path converters to return int or slug from string
         views.post_detail,
         name='post_detail'),
    # re_path(r'^index/$', views.index, name='index'),
    path('<int:post_id>/share/', views.post_share, name='post_share'), #email share url
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'), #use a slug path converter 
    path('feed/', LatestPostsFeed(), name='post_feed'), #instantiate the feed in a new URL pattern
    path('search/', views.post_search, name='post_search'),
] 
# http://127.0.0.1:8000/blog/feed/ 
# http://127.0.0.1:8000/blog/search/

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
#import sitemaps
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = { # defined a dictionary of sitemaps.
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap') #defined a sitemap URL pattern
]
# http://127.0.0.1:8000/sitemap.xml
# http://127.0.0.1:8000/admin/sites/site/ # to change domain name

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager): 
    def get_queryset(self): 
        # return super(PublishedManager, self).get_queryset().filter(status='published')
        return super().get_queryset().filter(status='published')

class Post(models.Model): 
    STATUS_CHOICES = ( 
        ('draft', 'Draft'), 
        ('published', 'Published'), 
    ) 
    title = models.CharField(max_length=250) 
    slug = models.SlugField(max_length=250,  
                            unique_for_date='publish') #prevent multiple posts from having the same slug for a given date.
    author = models.ForeignKey(User, #many-to-one relationship (many posts-to-one author). 
                               on_delete=models.CASCADE,
                               related_name='blog_posts') #specify the name of the reverse relationship
    body = models.TextField() 
    publish = models.DateTimeField(default=timezone.now) 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    status = models.CharField(max_length=10,  
                              choices=STATUS_CHOICES, 
                              default='draft') 
    
    objects = models.Manager() # The default manager. 
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager() #third-party TaggableManager, use for many-to-many relationship
    
    class Meta: 
        ordering = ('-publish',) #sort results in the publish field in (-)descending order by default

    def __str__(self): 
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model): 
    post = models.ForeignKey(Post, #many-to-one relationship
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80) 
    email = models.EmailField() 
    body = models.TextField() 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=True) 
 
    class Meta: 
        ordering = ('created',) 
 
    def __str__(self): 
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form): # 1. standard forms
    name = forms.CharField(max_length=25) #default  widget <input type="text"> HTML 
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea) #override the <input> widget


class CommentForm(forms.ModelForm): #2. ModelForm
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):  # 3. a standard form for postgres_based fulltext search
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from taggit.models import Tag
from .models import Post, Comment 
from .forms import EmailPostForm, CommentForm, SearchForm


# def post_list(request):
def post_list(request, tag_slug=None):   # add an optional tag_slug parameter
    # posts = Post.published.all()
    # return render(request,
    #               'blog/post/list.html',
    #               {'posts': posts})
    object_list = Post.published.all()

    tag = None #  has a None default value

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug) # get the specified Tag object 
        # filter the list of posts by the given tag, a many-to-many relationship,
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) #  instantiate the Paginator class with objects displaying 3 posts in each page
    page = request.GET.get('page')  # to get the current page number
    try:
        posts = paginator.page(page) # get posts within the targeted page -- current page
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


def post_detail(request, year, month, day, post):
    #get the specified post
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    # process and handle the comment modelForm
    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST) # instantiate the form using the submitted data
        if comment_form.is_valid(): # process and validate the form
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # before actually commite, Assign the current post to the comment
            new_comment.post = post
            #finally, Save the post related comment to the database
            new_comment.save()
    else: # if GET, build a form instance 
        comment_form = CommentForm()

    # List of similar posts
    #get tag ID list of the current post
    post_tags_ids = post.tags.values_list('id', flat=True) 
    # get all posts that contain any of these tags,excluding the current post
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                  .exclude(id=post.id) 
    #count the shared tags, order_by shared tags_publish date, retrieve first four posts                             
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                .order_by('-same_tags','-publish')[:4]

    # saved, or validate errors
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts}) #pass the similar posts


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_share(request, post_id): 
    # Retrieve post by id to be shared
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False  # flag hook
    # handling standard EmailPostForms to share post
    if request.method == 'POST': #standard form validate
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid(): # use is_valid() to validate the submitted data
            # Form fields passed validation
            cd = form.cleaned_data

            #  send email:
            post_url = request.build_absolute_uri( # get the url of the shared post
                                          post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']]) #use send_mail()
            sent = True # flag hook
    else:
        form = EmailPostForm() # if GET, an empty form instance is displayed
    # after send mail or If the form is not valid, render the form in the template 
    # with the submitted data or/and validation errors
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent
                                                    })


def post_search(request):
    form = SearchForm() # instantiate the SearchForm form
    query = None
    results = []
    if 'query' in request.GET: # To check whether the form is submitted
        form = SearchForm(request.GET) # instantiate form with the submitted GET data
        if form.is_valid():  # verify that the form data is valid
            query = form.cleaned_data['query']
            '''
            #1.search for posts with a custom  SearchVector 
            # instance built with the title and body fields
            # results = Post.objects.annotate(
            #     search=SearchVector('title', 'body'),
            # ).filter(search=query)

            #2. search for posts with SearchQuery for relavance ranking
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                        search=search_vector,
                        rank=SearchRank(search_vector, search_query)
                    ).filter(search=search_query).order_by('-rank')
            
            #3. search posts with pecific vectors for query weighting and relavance ranking
            # default D, C, B, A = 0.1, 0.2, 0.4, 1.0
            search_vector = SearchVector('title', 'body')
            search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            results = Post.objects.annotate(
                        search=search_vector,
                        rank=SearchRank(search_vector, search_query)
                    ).filter(rank__gte=0.3).order_by('-rank')
            '''
            #4.edit the blog/views.py and modify it to search for trigrams.
            results = Post.objects.annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.3).order_by('-similarity')
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

blog/templates/blog/post/detail.html
<!-- to inherit from the blog/base.html template. -->
{% extends "blog/base.html" %} 
<!-- load template tags module  -->
{% load blog_tags %}
 
{% block title %}{{ post.title }}{% endblock %} 
 
{% block content %} 
  <h1>{{ post.title }}</h1> 
  <p class="tags">
      Tags:
      <!-- list tags for this post with url links -->
      {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{ tag.name }}
        </a>
        <!-- separate the tags by commas -->
        {% if not forloop.last %}, {% endif %} 
      {% endfor %}
  </p>
  <p class="date"> 
    Published {{ post.publish }} by {{ post.author }} 
  </p> 
  <!-- {{ post.body|linebreaks }}  -->
  <!-- using custom template filter markdown -->
  {{ post.body|markdown }} 
  
  <p>
    <a href="{% url 'blog:post_share' post.id %}">
      Share this post
    </a>
  </p>
  
  <!-- display similar_posts with url links -->
  <h2>Similar posts</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
  {% empty %}
    There are no similar posts yet.
  {% endfor %}

  <!-- 1. Display the total number of comments for the post -->
   {% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
  {% endwith %}
  <!-- 2. Display the list of comments -->
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  <!-- display a default message if the comments list is empty -->
  {% empty %}
    <p>There are no comments yet.</p>
  {% endfor %}
  <!-- display a successful message -->
  {% if new_comment %}
    <h2>Your comment has been added.</h2>
  {% else %}
    <!-- to render the form -->
    <h2>Add a new comment</h2>
    <form action="." method="post">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Add comment"></p>
    </form>
  {% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
{% for post in latest_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
{% endfor %}
</ul>

blog/templates/blog/post/list.html
<!-- to inherit from the blog/base.html template. -->
{% extends "blog/base.html" %} 
<!-- load template tags module  -->
{% load blog_tags %}
 
{% block title %}My Blog{% endblock %}
 
{% block content %}
  <h1>My Blog</h1>
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}

  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <!-- <p class="tags">Tags: {{ post.tags.all|join:", " }}</p> -->
    <p class="tags">
      Tags:
      <!-- list tags for each post with url links -->
      {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{ tag.name }}
        </a>
        <!-- separate the tags by commas -->
        {% if not forloop.last %}, {% endif %} 
      {% endfor %}
    </p>

    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    <!-- {{ post.body|truncatewords:30|linebreaks }} -->
    <!-- using custom template filter markdown -->
    {{ post.body|markdown|truncatewords_html:30 }}
  {% endfor %}
  {% include "pagination.html" with page=posts %} 
  <!--  the Page object func view are passing to the template is posts -->
  <!-- {% include "pagination.html" with page=page_obj %}  -->
  <!--  the Page object class view are passing to the template is page_obj -->

{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
  <!-- form has been submitted: -->
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.body|truncatewords:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
  {% else %}
  <!-- if not submitted, display the form and a submit button -->
    <h1>Search for posts</h1>
    <form action="." method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form action="." method="post">
      {{ form.as_p }}

     <!-- # same as:
      {% for field in form %}
        <div>
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
        </div>
      {% endfor %} -->

      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}